spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 20s

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms